import os
from colors import CYAN, BOLD, DIM, GRN, RST
from llm_client import load_config

def show_help():
    config = load_config()
    version = config.get("version", "8b")
    mode = os.environ.get("ULTRON_LLM_MODE") or config.get("llm_mode", "local")
    print()
    print(f"  {CYAN}{BOLD}USAGE{RST}")
    print(f"  {DIM}──────────────────────────────────────────────────{RST}")
    print(f"    ultron <repository-url> [--verbose | -v | --debug | -d] [--mode local|cloud]")
    print(f"    ultron list")
    print(f"    ultron scan <repo-name> [--verbose | -v | --debug | -d] [--mode local|cloud]")
    print(f"    ultron delete <repo-name>")
    print(f"    ultron delete --all")
    print(f"    ultron visualise <repo-name> [--verbose | -v | --debug | -d] [--mode local|cloud]")
    print(f"    ultron visualize <repo-name> [--verbose | -v | --debug | -d] [--mode local|cloud]")
    print(f"    ultron config")
    print(f"    ultron config <part/setting> <value>")
    print(f"    ultron config reset [--mode local|cloud]")
    print(f"    ultron --help")
    print()
    print(f"  {CYAN}{BOLD}INTERACTIVE COMMANDS{RST}")
    print(f"  {DIM}──────────────────────────────────────────────────{RST}")
    print(f"    <url> [--verbose] [--mode ...]            clone a repository")
    print(f"    list                                      list cloned repositories")
    print(f"    scan <name> [--verbose] [--mode ...]      scan an already-cloned repository")
    print(f"    delete <repo-name>                        delete a cloned repository")
    print(f"    delete --all                              delete all cloned repositories")
    print(f"    visualise <name> [--verbose] [--mode ...] build and show dependency/taint graph")
    print(f"    config                                    show current configuration")
    print(f"    config <part/setting> <value>             change a model override or setting")
    print(f"    config reset                              reset configuration to defaults")
    print(f"    help                                      show this message")
    print(f"    exit / quit / bye                         exit the program")
    print()
    print(f"  {CYAN}{BOLD}CONFIGURATION SETTINGS{RST}")
    print(f"  {DIM}──────────────────────────────────────────────────{RST}")
    print(f"    Ultron allows configuring both local and cloud LLM providers:")
    print(f"    • {BOLD}classifier/detector/...{RST} : local model overrides for specific agents")
    print(f"    • {BOLD}visualise{RST}                  : toggle terminal graph visualisation")
    print(f"    • {BOLD}verbose{RST}                    : toggle detailed logging by default")
    print(f"    • {BOLD}temperature/timeout/etc.{RST} : standard LLM client parameters")
    print(f"    • {BOLD}llm_mode{RST}                   : {GRN}local{RST} (default) or {GRN}cloud{RST}")
    print(f"    • {BOLD}api_keys{RST}                   : set keys for {GRN}groq{RST}, {GRN}gemini{RST}, {GRN}nvidia{RST}")
    print(f"    • {BOLD}cloud_chain{RST}                : fallback order per agent (e.g. [groq, gemini])")
    print(f"    • {BOLD}cloud_models{RST}               : model name per cloud provider")
    print()
    print(f"  {CYAN}{BOLD}FLAGS{RST}")
    print(f"  {DIM}──────────────────────────────────────────────────{RST}")
    print(f"    {GRN}--verbose{RST}, {GRN}-v{RST}, {GRN}--debug{RST}, {GRN}-d{RST}  enable detailed tracing:")
    print(f"      • PatternPass manual pattern findings and matches")
    print(f"      • LLM prompts, raw outputs, and reasoning/thinking")
    print(f"      • LLM API connection errors/timeouts and fallback attempts")
    print(f"      • Step-by-step variables and taint propagation flow")
    print(f"    {GRN}--mode{RST} {GRN}local{RST}|{GRN}cloud{RST}           override LLM mode for this command")
    print(f"      (overrides {BOLD}llm_mode{RST} in config for one-off use)")
    print()
    print(f"  {CYAN}{BOLD}CLOUD MODE{RST}")
    print(f"  {DIM}──────────────────────────────────────────────────{RST}")
    print(f"    Use cloud LLM providers instead of local models.")
    print(f"    Two ways to enable:")
    print(f"      • Set {GRN}llm_mode: cloud{RST} in {GRN}ultron_config.json{RST} (persistent)")
    print(f"      • Pass {GRN}--mode cloud{RST} on any command (one-off)")
    print(f"    Providers are tried in fallback order; if one fails, the next is used.")
    print(f"    Supported: {GRN}Groq{RST}, {GRN}Gemini{RST}, {GRN}NVIDIA{RST}")
    print(f"    Set API keys via {GRN}config api_keys.groq <key>{RST} or edit ultron_config.json")
    print()
    print(f"  {CYAN}{BOLD}NOTES{RST}")
    print(f"  {DIM}──────────────────────────────────────────────────{RST}")
    print(f"    if a repository already exists locally, you will")
    print(f"    be prompted to pull latest changes instead.")
    print()
    print(f"  {CYAN}{BOLD}ABOUT{RST}")
    print(f"  {DIM}──────────────────────────────────────────────────{RST}")
    print(f"    ULTRON is a {GRN}local-first{RST} multi-agent security")
    print(f"    analysis engine. it clones a target repository,")
    print(f"    runs a hybrid pattern + LLM classifier,")
    print(f"    traces data flow using a taint propagation engine,")
    print(f"    and builds security dependency/taint diagrams.")
    print(f"    {DIM}version:{RST} {version}  {DIM}mode:{RST} {GRN}{mode}{RST}")
    print()
