from colors import CYAN, BOLD, DIM, GRN, RST
from llm_client import load_config

def show_help():
    config = load_config()
    version = config.get("version", "8b")
    print()
    print(f"  {CYAN}{BOLD}USAGE{RST}")
    print(f"  {DIM}──────────────────────────────────────────────────{RST}")
    print(f"    ultron <repository-url> [--verbose | -v | --debug | -d]")
    print(f"    ultron list")
    print(f"    ultron scan <repo-name> [--verbose | -v | --debug | -d]")
    print(f"    ultron delete <repo-name>")
    print(f"    ultron delete --all")
    print(f"    ultron visualise <repo-name> [--verbose | -v | --debug | -d]")
    print(f"    ultron visualize <repo-name> [--verbose | -v | --debug | -d]")
    print(f"    ultron config")
    print(f"    ultron config <part/setting> <value>")
    print(f"    ultron config reset")
    print(f"    ultron --help")
    print()
    print(f"  {CYAN}{BOLD}INTERACTIVE COMMANDS{RST}")
    print(f"  {DIM}──────────────────────────────────────────────────{RST}")
    print(f"    <url> [--verbose]              clone a repository")
    print(f"    list                           list cloned repositories")
    print(f"    scan <repo-name> [--verbose]   scan an already-cloned repository")
    print(f"    delete <repo-name>             delete a cloned repository")
    print(f"    delete --all                   delete all cloned repositories")
    print(f"    visualise <name> [--verbose]   build and show dependency/taint graph")
    print(f"    config                         show current configuration")
    print(f"    config <part/setting> <value>  change a model override or setting")
    print(f"    config reset                   reset configuration to defaults")
    print(f"    help                           show this message")
    print(f"    exit / quit / bye              exit the program")
    print()
    print(f"  {CYAN}{BOLD}CONFIGURATION SETTINGS{RST}")
    print(f"  {DIM}──────────────────────────────────────────────────{RST}")
    print(f"    Ultron allows configuring local LLM details and settings:")
    print(f"    • {BOLD}classifier/detector/...{RST} : local model overrides for specific agents")
    print(f"    • {BOLD}visualise{RST}                  : toggle terminal graph visualisation")
    print(f"    • {BOLD}verbose{RST}                    : toggle detailed logging by default")
    print(f"    • {BOLD}temperature/timeout/etc.{RST} : standard LLM client parameters")
    print()
    print(f"  {CYAN}{BOLD}VERBOSE / DEBUG FLAGS{RST}")
    print(f"  {DIM}──────────────────────────────────────────────────{RST}")
    print(f"    Passing {GRN}--verbose{RST} or {GRN}-v{RST} enables detailed tracing:")
    print(f"    • PatternPass manual pattern findings and matches")
    print(f"    • Local LLM prompts, raw outputs, and reasoning/thinking")
    print(f"    • LLM API connection errors/timeouts")
    print(f"    • Step-by-step variables and taint propagation flow")
    print()
    print(f"  {CYAN}{BOLD}NOTES{RST}")
    print(f"  {DIM}──────────────────────────────────────────────────{RST}")
    print(f"    if a repository already exists locally, you will")
    print(f"    be prompted to pull latest changes instead.")
    print()
    print(f"  {CYAN}{BOLD}ABOUT{RST}")
    print(f"  {DIM}──────────────────────────────────────────────────{RST}")
    print(f"    ULTRON is a {GRN}local-first{RST} multi-agent security")
    print(f"    analysis engine. it clones a target repository,")
    print(f"    runs a hybrid pattern + local LLM classifier,")
    print(f"    traces data flow using a taint propagation engine,")
    print(f"    and builds security dependency/taint diagrams.")
    print(f"    {DIM}version:{RST} {version}  {DIM}mode:{RST} {GRN}local-first{RST}")
    print()
