from colors import CYAN, BOLD, DIM, GRN, RST

def show_help():
    print()
    print(f"  {CYAN}{BOLD}USAGE{RST}")
    print(f"  {DIM}──────────────────────────────────────────────────{RST}")
    print(f"    ultron <repository-url>")
    print(f"    ultron list")
    print(f"    ultron scan <repo-name>")
    print(f"    ultron delete <repo-name>")
    print(f"    ultron delete --all")
    print(f"    ultron --help")
    print()
    print(f"  {CYAN}{BOLD}INTERACTIVE COMMANDS{RST}")
    print(f"  {DIM}──────────────────────────────────────────────────{RST}")
    print(f"    <url>              clone a repository")
    print(f"    list               list cloned repositories")
    print(f"    scan <repo-name>   scan an already-cloned repository")
    print(f"    delete <repo-name> delete a cloned repository")
    print(f"    delete --all       delete all cloned repositories")
    print(f"    help               show this message")
    print(f"    exit / quit / bye  exit the program")
    print()
    print(f"  {CYAN}{BOLD}NOTES{RST}")
    print(f"  {DIM}──────────────────────────────────────────────────{RST}")
    print(f"    if a repository already exists locally, you will")
    print(f"    be prompted to pull latest changes instead.")
    print()
    print(f"  {CYAN}{BOLD}ABOUT{RST}")
    print(f"  {DIM}──────────────────────────────────────────────────{RST}")
    print(f"    ULTRON is a {GRN}local-first{RST} multi-agent security")
    print(f"    analysis engine. it clones a target repository")
    print(f"    and runs 6 specialized security agents powered")
    print(f"    by a local 8B LLM to detect vulnerabilities,")
    print(f"    generate exploits, and produce a final report.")
    print(f"    {DIM}version:{RST} 8b  {DIM}mode:{RST} {GRN}local-first{RST}")
    print()
